/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventorymanagementsystem;

import javax.swing.ImageIcon;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author LoneDespair
 */
public class CartGrocery extends javax.swing.JPanel implements ProductEvent{
    Grocery grocery;
    Product product;
    
    ImageIcon imageIcon = null;
    CartPage cartPage;
    
    /**
     * Creates new form CartGrocery
     */
    public CartGrocery() {
        initComponents();
    }
    
    public CartGrocery(Grocery newGrocery, CartPage newCartPage) {
        this();
        grocery = newGrocery;
        product = newGrocery.product;
        cartPage = newCartPage;
        
        product.listeners.add(this);
        update();
    }
    
    public void update() {
        if (product.quantity == 0) {
            remove();
            
        } else {
            nameLabel.setText(product.name);
            priceLabel.setText(Money.format(product.price));
            imageIcon = FallbackIcon.getIcon(product.image);
            
            SpinnerNumberModel model = (SpinnerNumberModel) countSpinner.getModel();
            
            model.setValue(Math.min(product.quantity, grocery.count));
            model.setMaximum(product.quantity);
            
            updateCount();
        }
    }
    
    public void append(Grocery newGrocery) {
        grocery.count += newGrocery.count;
        updateCount();
    }
    
    public void updateCount() {
        countSpinner.setValue(grocery.count);
        totalLabel.setText(Money.format(product.price * grocery.count));
        cartPage.updateSummary();
    }

    @Override
    public void onEvent(Type type) {
        if (type == Type.DELETE) remove();
        else if (type == Type.MODIFY) update();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holder = new javax.swing.JPanel();
        remove = new javax.swing.JButton();
        countSpinner = new javax.swing.JSpinner();
        displayIcon = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(32767, 123));
        setMinimumSize(new java.awt.Dimension(500, 123));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 123));
        setRequestFocusEnabled(false);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });

        holder.setBackground(new java.awt.Color(252, 249, 190));
        holder.setMinimumSize(new java.awt.Dimension(0, 117));
        holder.setPreferredSize(new java.awt.Dimension(500, 117));
        holder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        remove.setBackground(new java.awt.Color(250, 219, 216));
        remove.setForeground(new java.awt.Color(102, 102, 102));
        remove.setText("Remove");
        remove.setFocusable(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        holder.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        countSpinner.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        countSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        countSpinner.setMinimumSize(new java.awt.Dimension(50, 26));
        countSpinner.setPreferredSize(new java.awt.Dimension(50, 26));
        countSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                countSpinnerStateChanged(evt);
            }
        });
        holder.add(countSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 80, 20));

        displayIcon.setBackground(new java.awt.Color(255, 220, 169));
        displayIcon.setOpaque(true);
        displayIcon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                displayIconComponentResized(evt);
            }
        });
        holder.add(displayIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 105, 105));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel.setText("Product name");
        holder.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 123, -1));

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(250, 171, 121));
        priceLabel.setText("₱0.00");
        holder.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 215, -1));

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(250, 171, 121));
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalLabel.setText("₱0.00");
        holder.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(holder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void remove() {
        if (cartPage == null){ System.out.println("Cart page not found"); }
        else { cartPage.removeCartGrocery(this); }
    }
    
    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        remove();
    }//GEN-LAST:event_removeActionPerformed

    private void displayIconComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_displayIconComponentResized
        displayIcon.setIcon(ImageResizer.fitImageIcon(imageIcon, displayIcon.getSize()));
    }//GEN-LAST:event_displayIconComponentResized

    private void countSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_countSpinnerStateChanged
        grocery.count = (Integer) countSpinner.getValue();
        
        totalLabel.setText(Money.format(product.price * grocery.count));
        cartPage.updateSummary();
    }//GEN-LAST:event_countSpinnerStateChanged

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        product.listeners.remove(this);
    }//GEN-LAST:event_formComponentRemoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner countSpinner;
    private javax.swing.JLabel displayIcon;
    private javax.swing.JPanel holder;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton remove;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
