/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventorymanagementsystem;

/**
 *
 * @author LoneDespair
 */
public class CartGrocery extends javax.swing.JPanel {
    Grocery grocery;
    CartPage cartPage;
    
    /**
     * Creates new form CartGrocery
     */
    public CartGrocery() {
        initComponents();
    }
    
    public CartGrocery(Grocery newGrocery, CartPage newCartPage) {
        this();
        grocery = newGrocery;
        cartPage = newCartPage;
        update();
    }
    
    public void append(Grocery newGrocery) {
        grocery.count += newGrocery.count;
    }
    
    public void update() {
        Product product = grocery.product;
        nameLabel.setText(product.name);
        priceLabel.setText(product.getStringPrice());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holder = new javax.swing.JPanel();
        remove = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        icon = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setEnabled(false);
        setMaximumSize(new java.awt.Dimension(32767, 123));
        setMinimumSize(new java.awt.Dimension(500, 123));
        setName(""); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 123));
        setRequestFocusEnabled(false);

        holder.setBackground(new java.awt.Color(252, 249, 190));
        holder.setMinimumSize(new java.awt.Dimension(0, 117));
        holder.setPreferredSize(new java.awt.Dimension(500, 117));
        holder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        remove.setForeground(new java.awt.Color(102, 102, 102));
        remove.setText("Remove");
        remove.setFocusable(false);
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        holder.add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jSpinner1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jSpinner1.setPreferredSize(new java.awt.Dimension(90, 26));
        holder.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 14, 90, -1));

        icon.setBackground(new java.awt.Color(255, 220, 169));
        icon.setOpaque(true);
        holder.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 105, 105));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel.setText("Product name");
        holder.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 15, 123, -1));

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(250, 171, 121));
        priceLabel.setText("₱0.00");
        holder.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 215, -1));

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalLabel.setForeground(new java.awt.Color(250, 171, 121));
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        totalLabel.setText("₱0.00");
        holder.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 15, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(holder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(holder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        if (cartPage == null){ System.out.println("Cart page not found"); }
        else {
            int id = grocery.product.id;
            cartPage.table.remove(id);
            cartPage.removeCartGrocery(this);
            //this.remove(this);
        }
    }//GEN-LAST:event_removeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel holder;
    private javax.swing.JLabel icon;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton remove;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
