/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventorymanagementsystem;

import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author LoneDespair
 */
public class PurchaseOption extends javax.swing.JPanel {
    Color transparent = new Color(0, 0, 0, 0);
    ImageIcon imageIcon = null;
    Product product;
    
    CartPage cartPage;
    
    
    /**
     * Creates new form PurchaseOption
     */
    public PurchaseOption() {
        initComponents();
        
        //inputConsumer.setBackground(transparent);
        bg.setBackground(new Color(23, 32, 42, 100));
    }
    
    public PurchaseOption(CartPage newCartPage) {
        this();
        cartPage = newCartPage;
    }
    
    
    public void open(Product newProduct) {
        setVisible(true);
        countSpinner.setValue(1);
        product = newProduct;
        
        nameLabel.setText(newProduct.name);
        priceLabel.setText(Money.format(newProduct.price));
        imageIcon = FallbackIcon.getIcon(newProduct.image);
        displayIcon.setIcon(ImageResizer.fitImageIcon(imageIcon, displayIcon.getSize()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new inventorymanagementsystem.InputConsumer();
        displayIcon = new javax.swing.JLabel();
        countSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        cartButton = new javax.swing.JButton();
        coloredButton1 = new inventorymanagementsystem.ColoredButton();
        bg = new inventorymanagementsystem.InputConsumer();

        setBackground(new java.awt.Color(51, 51, 255));
        setLayout(new javax.swing.OverlayLayout(this));

        content.setBackground(new java.awt.Color(252, 249, 190));
        content.setMaximumSize(new java.awt.Dimension(624, 250));
        content.setMinimumSize(new java.awt.Dimension(624, 250));
        content.setPreferredSize(new java.awt.Dimension(624, 250));

        displayIcon.setBackground(new java.awt.Color(255, 220, 169));
        displayIcon.setOpaque(true);
        displayIcon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                displayIconComponentResized(evt);
            }
        });

        countSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        countSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        countSpinner.setMaximumSize(new java.awt.Dimension(75, 32767));
        countSpinner.setMinimumSize(new java.awt.Dimension(75, 22));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Quantity");

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel.setText("Name of product here");
        nameLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(250, 171, 121));
        priceLabel.setText("₱0.00");

        cartButton.setForeground(new java.awt.Color(102, 102, 102));
        cartButton.setText("Add to cart");
        cartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartButtonActionPerformed(evt);
            }
        });

        coloredButton1.setText("X");
        coloredButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        coloredButton1.setMaximumSize(new java.awt.Dimension(27, 27));
        coloredButton1.setMinimumSize(new java.awt.Dimension(27, 27));
        coloredButton1.setPreferredSize(new java.awt.Dimension(15, 15));
        coloredButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coloredButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(coloredButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(priceLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cartButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(countSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(213, Short.MAX_VALUE))))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                    .addContainerGap(24, Short.MAX_VALUE)
                    .addComponent(displayIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(400, Short.MAX_VALUE)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel)
                .addGap(32, 32, 32)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(countSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(coloredButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                    .addContainerGap(25, Short.MAX_VALUE)
                    .addComponent(displayIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        add(content);

        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bgMouseMoved(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 753, Short.MAX_VALUE)
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );

        add(bg);
    }// </editor-fold>//GEN-END:initComponents

    private void cartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartButtonActionPerformed
        if (cartPage == null) System.out.println("Null cartPage on purchaseOption");
        else{
            cartPage.addGrocery(new Grocery(product, (Integer)countSpinner.getValue()));
            setVisible(false);
        }
    }//GEN-LAST:event_cartButtonActionPerformed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        setVisible(false);
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseMoved
           
    }//GEN-LAST:event_bgMouseMoved

    private void coloredButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloredButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_coloredButton1ActionPerformed

    private void displayIconComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_displayIconComponentResized
        displayIcon.setIcon(ImageResizer.fitImageIcon(imageIcon, displayIcon.getSize()));
    }//GEN-LAST:event_displayIconComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private inventorymanagementsystem.InputConsumer bg;
    private javax.swing.JButton cartButton;
    private inventorymanagementsystem.ColoredButton coloredButton1;
    private inventorymanagementsystem.InputConsumer content;
    private javax.swing.JSpinner countSpinner;
    private javax.swing.JLabel displayIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
