/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventorymanagementsystem;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import java.awt.Image;

/**
 *
 * @author LoneDespair
 */
public class PurchaseProduct extends javax.swing.JPanel {
    PurchaseOption purchaseOption = null;
    
    Product product;
    ImageIcon imageIcon = null;
    
    
    /**
     * Creates new form PurchaseProduct
     */
    public PurchaseProduct() {
        initComponents();
    }
    
    public PurchaseProduct(Product newProduct, PurchaseOption newPurchaseOption) {
        initComponents();
        product = newProduct;
        nameLabel.setText(product.name);
        priceLabel.setText(product.getStringPrice());
        
        imageIcon = FallbackIcon.getIcon(product.image);
        
        //imageIcon = new ImageIcon(newProduct.image);
        purchaseOption = newPurchaseOption;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        holder = new javax.swing.JPanel();
        button = new inventorymanagementsystem.ColoredButton();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        displayIcon = new javax.swing.JLabel();

        setEnabled(false);
        setFocusable(false);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(195, 255));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        holder.setBackground(new java.awt.Color(252, 249, 190));
        holder.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        holder.setDoubleBuffered(false);
        holder.setEnabled(false);
        holder.setFocusable(false);
        holder.setMinimumSize(new java.awt.Dimension(0, 0));
        holder.setPreferredSize(new java.awt.Dimension(160, 220));
        holder.setRequestFocusEnabled(false);
        holder.setVerifyInputWhenFocusTarget(false);
        holder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                holderMouseMoved(evt);
            }
        });
        holder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                holderMouseClicked(evt);
            }
        });
        holder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button.setFocusPainted(false);
        button.setRequestFocusEnabled(false);
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
        });
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        holder.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 175, 235));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(102, 102, 102));
        nameLabel.setText("Selecta Ice cream");
        holder.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 30));

        priceLabel.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        priceLabel.setForeground(new java.awt.Color(250, 171, 121));
        priceLabel.setText("₱150.00");
        holder.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 130, 30));

        displayIcon.setBackground(new java.awt.Color(255, 220, 169));
        displayIcon.setFocusable(false);
        displayIcon.setOpaque(true);
        displayIcon.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                displayIconComponentResized(evt);
            }
        });
        holder.add(displayIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 155, 155));

        add(holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 175, 235));
    }// </editor-fold>//GEN-END:initComponents

    private void displayIconComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_displayIconComponentResized
        displayIcon.setIcon(ImageResizer.fitImageIcon(imageIcon, displayIcon.getSize()));
    }//GEN-LAST:event_displayIconComponentResized

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        if (purchaseOption == null) System.out.println("Purchase option is null");
        else {
            button.getModel().setArmed(false);
            button.getModel().setRollover(false);
            button.getModel().setSelected(false);
            button.getModel().setPressed(false);
            purchaseOption.open(product);
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed

    }//GEN-LAST:event_buttonMousePressed

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked

    }//GEN-LAST:event_buttonMouseClicked

    private void holderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_holderMouseClicked
        System.out.println("HOLDER CLICKED");
    }//GEN-LAST:event_holderMouseClicked

    private void holderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_holderMouseMoved
        System.out.println("HOLDER CLICKED");
    }//GEN-LAST:event_holderMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private inventorymanagementsystem.ColoredButton button;
    private javax.swing.JLabel displayIcon;
    private javax.swing.JPanel holder;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
