/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventorymanagementsystem;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.reflect.Array;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Scanner;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author LoneDespair
 */
public class User extends javax.swing.JPanel {
    Users use = new Users();
    UserFile updater = new UserFile();
    String listFilePath = Paths.get(System.getProperty("user.dir"),"src/inventorymanagementsystem","Users.txt").toString();
    String tempFilePath = Paths.get(System.getProperty("user.dir"),"src/inventorymanagementsystem","temp.txt").toString();
    HashMap <Integer, Users> hashTable = new HashMap <Integer, Users>();    
    DefaultTableModel model;
    JTable table;
    
    JComponent home;
    
    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        populate();
        sort();
        tableDisplay();
    }

    private void sort() {
        model = (DefaultTableModel)userTbl.getModel();
        table = userTbl;
        TableRowSorter <DefaultTableModel> sorter = new TableRowSorter <DefaultTableModel> (model);
        table.setRowSorter(sorter);
    }
    
    private void populate() {
        String userLine = new String();
        String[] userDetails = new String[3];
        model = (DefaultTableModel)userTbl.getModel();
        int i;
        try(FileReader file = new FileReader(listFilePath)) {            
            Scanner scan = new Scanner(file);                                   
            for(i=model.getRowCount()-1; i>=0; i--)
                model.removeRow(i);
                    
            while(scan.hasNext()) {
                userLine = scan.nextLine();
                userDetails = userLine.split("\\s+");
                model.addRow(userDetails);                                       
            }             
            file.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void tableDisplay(){
        userTbl.getColumnModel().getColumn(1).setMinWidth(0);
        userTbl.getColumnModel().getColumn(1).setMaxWidth(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        upass = new javax.swing.JPasswordField();
        uName = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();
        Editbtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userTbl = new javax.swing.JTable();
        usearch = new javax.swing.JTextField();
        search = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        selectName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        selectPass = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        claerbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(232, 243, 214));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(250, 171, 120));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(800, 112));
        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeButton.setBackground(new java.awt.Color(250, 171, 120));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/menu.png"))); // NOI18N
        homeButton.setBorderPainted(false);
        homeButton.setPreferredSize(new java.awt.Dimension(112, 112));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        HeaderPanel.add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(232, 243, 214));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MANAGE USERS");
        HeaderPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 112));

        add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 171, 120));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Username:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 215, 132, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 171, 120));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 246, 110, -1));

        upass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        upass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upassActionPerformed(evt);
            }
        });
        add(upass, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 246, 200, -1));

        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });
        add(uName, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 218, 200, -1));

        Addbtn.setBackground(new java.awt.Color(255, 220, 169));
        Addbtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Addbtn.setText("ADD");
        Addbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddbtnMouseClicked(evt);
            }
        });
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 288, -1, -1));

        Editbtn.setBackground(new java.awt.Color(255, 220, 169));
        Editbtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Editbtn.setText("EDIT");
        Editbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditbtnMouseClicked(evt);
            }
        });
        Editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditbtnActionPerformed(evt);
            }
        });
        add(Editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 414, -1, -1));

        Deletebtn.setBackground(new java.awt.Color(255, 220, 169));
        Deletebtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Deletebtn.setText("DELETE");
        Deletebtn.setToolTipText("");
        Deletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Deletebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletebtnMouseClicked(evt);
            }
        });
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });
        add(Deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 414, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 171, 120));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USERS LIST");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 403, -1));

        userTbl.setBackground(new java.awt.Color(252, 249, 190));
        userTbl.setFont(new java.awt.Font("Century Gothic", 0, 20)); // NOI18N
        userTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password"
            }
        ));
        userTbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userTbl.setGridColor(new java.awt.Color(250, 171, 120));
        userTbl.setRowHeight(25);
        userTbl.setSelectionBackground(new java.awt.Color(250, 171, 120));
        userTbl.setSelectionForeground(new java.awt.Color(252, 249, 190));
        userTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(userTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 152, 403, 346));

        usearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usearchKeyReleased(evt);
            }
        });
        add(usearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(543, 152, 239, -1));

        search.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(250, 171, 120));
        search.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        search.setText("Search:");
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 152, 87, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 171, 120));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Username:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 347, 110, -1));

        selectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectNameActionPerformed(evt);
            }
        });
        add(selectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 347, 200, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 171, 120));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Password:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 377, 110, -1));

        selectPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        selectPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPassActionPerformed(evt);
            }
        });
        add(selectPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(582, 380, 200, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Modify User Information");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 322, 361, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Add User Information");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 190, -1, -1));

        claerbtn.setBackground(new java.awt.Color(255, 220, 169));
        claerbtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        claerbtn.setText("CLEAR LIST");
        claerbtn.setToolTipText("");
        claerbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        claerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claerbtnMouseClicked(evt);
            }
        });
        claerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claerbtnActionPerformed(evt);
            }
        });
        add(claerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 504, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void upassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upassActionPerformed

    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameActionPerformed

    private void AddbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddbtnMouseClicked
        if(!uName.getText().isEmpty() && !upass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Missing Information");
            return;
        }
    }//GEN-LAST:event_AddbtnMouseClicked

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        model = (DefaultTableModel)userTbl.getModel();
        table = userTbl;
        String[] userDetails = new String[4];
        String newName = uName.getText();
        char[] newPass = upass.getPassword();

        int i;
        for(i=0; i<=model.getRowCount()-1; i++) {
            if(String.valueOf(model.getValueAt(i, 0)).equalsIgnoreCase(newName)) {
                JOptionPane.showMessageDialog(null, String.format("Item with name %s already exists.", uName.getText().toUpperCase()));
                return;
            }
        }

        if(!uName.getText().isEmpty() && !upass.getText().isEmpty()) {
            use.name = newName;
            use.pass = String.valueOf(newPass).toCharArray();

            userDetails[0] = use.name;
            userDetails[1] = String.copyValueOf(use.pass);

            model.addRow(userDetails);
            uName.setText(null);
            upass.setText(null);

            JOptionPane.showMessageDialog(null, "User Successfully Added.");
            updater.update(model, table);
        }
        else {
            JOptionPane.showMessageDialog(null, "Missing Information");
            return;
        }
    }//GEN-LAST:event_AddbtnActionPerformed

    private void EditbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditbtnMouseClicked

    }//GEN-LAST:event_EditbtnMouseClicked

    private void EditbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditbtnActionPerformed
        model = (DefaultTableModel)userTbl.getModel();
        table = (JTable)userTbl;
        int Myindex = table.getSelectedRow();

        if(Myindex == -1) {
            JOptionPane.showMessageDialog(null, "Please select an item.");
            return;
        }
        String editName = selectName.getText();
        String editPass = String.valueOf(selectPass.getPassword());

        if(!editName.isEmpty() && !editPass.isEmpty()) {
            model.setValueAt(editName.toUpperCase(), Myindex, 0);
            model.setValueAt(editPass, Myindex, 1);
            updater.update(model, table);

            JOptionPane.showMessageDialog(null, "User Information Successfully Edited.");
        }
        else
        JOptionPane.showMessageDialog(null, "Missing Informaion");
    }//GEN-LAST:event_EditbtnActionPerformed

    private void DeletebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletebtnMouseClicked

    }//GEN-LAST:event_DeletebtnMouseClicked

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed
        model = (DefaultTableModel)userTbl.getModel();
        table = (JTable)userTbl;
        int rowSelected = table.getSelectedRow();
        if(rowSelected!=-1) {
            model.removeRow(rowSelected);
            int i;
            updater.update(model, table);

            JOptionPane.showMessageDialog(null, "Successfully Deleted.");
        }
        else
        JOptionPane.showMessageDialog(null, "Please select an item.");
    }//GEN-LAST:event_DeletebtnActionPerformed

    private void userTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTblMouseClicked
        model = (DefaultTableModel)userTbl.getModel();
        int Myindex = userTbl.getSelectedRow();
        selectName.setText (model.getValueAt(Myindex, 0).toString());
        selectPass.setText(model.getValueAt(Myindex, 1).toString());
    }//GEN-LAST:event_userTblMouseClicked

    private void usearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usearchKeyReleased
        model = (DefaultTableModel)userTbl.getModel();
        table = (JTable)userTbl;
        String search = usearch.getText().toUpperCase();
        TableRowSorter <DefaultTableModel> sorter = new TableRowSorter <DefaultTableModel> (model);
        table.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_usearchKeyReleased

    private void selectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectNameActionPerformed

    private void selectPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPassActionPerformed

    private void claerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claerbtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_claerbtnMouseClicked

    private void claerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claerbtnActionPerformed
        model = (DefaultTableModel)userTbl.getModel();
        table = (JTable)userTbl;
        for(int i=model.getRowCount()-1; i>=0; i--)
        model.removeRow(i);
        updater.update(model, table);
    }//GEN-LAST:event_claerbtnActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        if (home == null) System.out.println("Null home on User");
        else {
            home.setVisible(true);
            setVisible(false);
        }
    }//GEN-LAST:event_homeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JButton Editbtn;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JButton claerbtn;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel search;
    private javax.swing.JTextField selectName;
    private javax.swing.JPasswordField selectPass;
    private javax.swing.JTextField uName;
    private javax.swing.JPasswordField upass;
    private javax.swing.JTextField usearch;
    private javax.swing.JTable userTbl;
    // End of variables declaration//GEN-END:variables
}
