/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventorysystem;

import java.nio.file.Paths;

/**
 *
 * @author BWISITA
 */
public class PurchasePage extends javax.swing.JPanel {
    
    static final String path = Paths.get(System.getProperty("user.dir"), "src/main/java/inventorysystem/Default.png").toString();
    
    /**
     * Creates new form PurchasePage
     */
    public PurchasePage() {
        initComponents();
        purchaseSelection.setup(purchaseOption);
        purchaseOption.setVisible(false);
        
        for (int idx = 0; idx < 3; idx++) {
            Product product = new Product();
            product.loadIcon(path);
            purchaseSelection.addProduct(product);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        purchaseOption = new inventorysystem.PurchaseOption();
        purchaseSelection = new inventorysystem.PurchaseSelection();

        setLayout(new javax.swing.OverlayLayout(this));
        add(purchaseOption);
        add(purchaseSelection);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private inventorysystem.PurchaseOption purchaseOption;
    private inventorysystem.PurchaseSelection purchaseSelection;
    // End of variables declaration//GEN-END:variables
}
