/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorysystem;

import javax.swing.ImageIcon;

/**
 *
 * @author LoneDespair
 */
public class JImagePicker extends javax.swing.JPanel {

    /**
     * Creates new form JImagePicker
     */
    public JImagePicker() {
        initComponents();
        
        /*
        // imageIcon = new ImageIcon("C:/Users/LoneDespair/Downloads/icecream_1.jpg");
        if (fileChooser.showSaveDialog(content) == 0) {
            ImageIcon imageIcon = new ImageIcon(fileChooser.getSelectedFile().getAbsolutePath());
            
            //imageIcon.toString()
        }*/
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new com.mycompany.inventorysystem.InputConsumer();
        fileChooser = new javax.swing.JFileChooser();
        inputConsumer1 = new com.mycompany.inventorysystem.InputConsumer();

        setBackground(new java.awt.Color(255, 255, 204));
        setOpaque(false);
        setLayout(new javax.swing.OverlayLayout(this));

        content.setMaximumSize(new java.awt.Dimension(550, 350));
        content.setMinimumSize(new java.awt.Dimension(550, 350));
        content.setPreferredSize(new java.awt.Dimension(550, 350));

        fileChooser.setBackground(new java.awt.Color(204, 255, 255));
        fileChooser.setCurrentDirectory(null);
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        add(content);

        javax.swing.GroupLayout inputConsumer1Layout = new javax.swing.GroupLayout(inputConsumer1);
        inputConsumer1.setLayout(inputConsumer1Layout);
        inputConsumer1Layout.setHorizontalGroup(
            inputConsumer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        inputConsumer1Layout.setVerticalGroup(
            inputConsumer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        add(inputConsumer1);
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        System.out.println("File evebtt");
        
    }//GEN-LAST:event_fileChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.inventorysystem.InputConsumer content;
    private javax.swing.JFileChooser fileChooser;
    private com.mycompany.inventorysystem.InputConsumer inputConsumer1;
    // End of variables declaration//GEN-END:variables
}
