/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.inventorysystem;

/**
 *
 * @author LoneDespair
 */
public class PurchasePage extends javax.swing.JPanel {
    
    /**
     * Creates new form PurchasePage
     */
    public PurchasePage() {
        initComponents();
        
        PurchaseProduct purchaseProduct = new PurchaseProduct();
        shelf.add(purchaseProduct);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        shelf = new javax.swing.JPanel();
        purchaseProduct1 = new com.mycompany.inventorysystem.PurchaseProduct();
        purchaseProduct7 = new com.mycompany.inventorysystem.PurchaseProduct();
        purchaseProduct5 = new com.mycompany.inventorysystem.PurchaseProduct();
        purchaseProduct2 = new com.mycompany.inventorysystem.PurchaseProduct();
        purchaseProduct3 = new com.mycompany.inventorysystem.PurchaseProduct();
        purchaseProduct4 = new com.mycompany.inventorysystem.PurchaseProduct();
        purchaseProduct6 = new com.mycompany.inventorysystem.PurchaseProduct();
        footer = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        header.setBackground(new java.awt.Color(250, 171, 121));
        header.setMaximumSize(new java.awt.Dimension(32767, 100));
        header.setMinimumSize(new java.awt.Dimension(0, 100));
        header.setPreferredSize(new java.awt.Dimension(576, 100));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(232, 243, 214));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PURCHASE");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        add(header);

        shelf.setBackground(new java.awt.Color(232, 243, 214));
        shelf.setLayout(new java.awt.GridLayout(2, 2));
        shelf.add(purchaseProduct1);
        shelf.add(purchaseProduct7);
        shelf.add(purchaseProduct5);
        shelf.add(purchaseProduct2);
        shelf.add(purchaseProduct3);
        shelf.add(purchaseProduct4);
        shelf.add(purchaseProduct6);

        jScrollPane1.setViewportView(shelf);

        add(jScrollPane1);

        footer.setBackground(new java.awt.Color(255, 220, 169));
        footer.setMaximumSize(new java.awt.Dimension(32767, 75));
        footer.setMinimumSize(new java.awt.Dimension(100, 50));
        footer.setPreferredSize(new java.awt.Dimension(961, 75));

        jButton1.setText("Add to cart");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(639, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        add(footer);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.mycompany.inventorysystem.PurchaseProduct purchaseProduct1;
    private com.mycompany.inventorysystem.PurchaseProduct purchaseProduct2;
    private com.mycompany.inventorysystem.PurchaseProduct purchaseProduct3;
    private com.mycompany.inventorysystem.PurchaseProduct purchaseProduct4;
    private com.mycompany.inventorysystem.PurchaseProduct purchaseProduct5;
    private com.mycompany.inventorysystem.PurchaseProduct purchaseProduct6;
    private com.mycompany.inventorysystem.PurchaseProduct purchaseProduct7;
    private javax.swing.JPanel shelf;
    // End of variables declaration//GEN-END:variables
}
